---
# tasks file for ios_12.2_hardening_role
#
#+ no service pad
#+ ip ssh version 2
#+ no ip domain-lookup
#+ no ip http server
#+ no ip http secure-server
#+ no cdp run
#+ transport input ssh
#+ logging buffered 15000
#+ service password-encryption
#+ set a login banner


  - name: DEFINE PROVIDER
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"


 
  - name: NO SERVICE PAD
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      lines:
        - no service pad

  - name: IP SSH VERSION 2
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      lines:
        - ip ssh version 2

  - name: NO IP DOMAIN-LOOKUP
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      lines:
        - no ip domain-lookup

  - name: DISABLE HTTP/HTTPS MANAGMENT
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      lines:
        - no ip http server
        - no ip http secure-server

  - name: DISABLE CDP 
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      lines:
        - no cdp run

  - name: TRANSPORT INPUT SSH
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      lines:
        - line vty 0 15
        - transport input ssh

  - name: LOGGING BUFFERED 15000
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      lines:
        - logging buffered 15000

  - name: SERVICE PASSWORD ENCRYPTION
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      lines:
        - service password-encryption

  - name: CONFIGURE BANNER FROM FILE
    ios_banner:
      provider: "{{ provider }}"
      authorize: yes
      banner: login
      text: "{{ lookup('file', './vars/raw_banner.cfg') }}"
      state: present
      
  - name: SHOW RUN | BEG BANNER
    ios_command:
      provider: "{{ provider }}"
      authorize: yes
      commands:
        - show run | beg banner
    register: banner

  - debug: var=banner.stdout_lines:     
        
        
        

 
